CIAO HENRI, QUESTO PROGETTO AL MOMENTO L'HO FATTO AL MEGLIO CHE POTEVO, SEPPUR AIUTANDOMI TANTO COME IN TUTTO IL PERCORSO.
AL MOMENTO NON SO SE MANCHI ALTRO O CI SIA ABBASTANZA PER FARLO ANDAR BENE MA,
VOLEVO INFORMARTI CHE LO PASSO ANCHE NELLA SETTIMANA S6-L5 OLTRE CHE ALLA SETTIMANA S7-L5,
CREDO CHE POSSA ANDAR BENE ANCHE IN QUELLA SETTIMANA VISTO CHE NON HO AVUTO MODO DI FARNE UN'ALTRO
E DATO CHE HO PERSO IL FILE CHE TI FACI VEDERE SUL PROGETTO, CHE TRA L'ALTRO FUNZIONAVA, DELLA PRIMA SETTIMANA DI LARAVEL A CAUSA DI BREEZE..
GRAZIE DI TUTTI I CONSIGLI HENRI